-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    id "char" NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    employer_id integer NOT NULL,
    companyname character varying NOT NULL,
    address character varying NOT NULL,
    email character varying NOT NULL,
    website character varying NOT NULL,
    telephonenumber character varying NOT NULL,
    password character varying NOT NULL,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public."JopSeeker"
(
    firstname character varying NOT NULL,
    lastaname character varying NOT NULL,
    nationalidentityno character varying NOT NULL,
    email character varying NOT NULL,
    dateofbirth date NOT NULL,
    "jopseeker-id" integer NOT NULL,
    PRIMARY KEY ("jopseeker-id")
);

CREATE TABLE public.recruitments
(
    "position-id" character varying NOT NULL,
    position_details character varying NOT NULL,
    PRIMARY KEY ("position-id")
);

CREATE TABLE public.system_personnels
(
    personnel_id integer NOT NULL,
    personnel_name character varying NOT NULL,
    personnel_lastname character varying NOT NULL,
    PRIMARY KEY (personnel_id)
);

CREATE TABLE public.verification_for_employers
(
    id integer NOT NULL,
    verification_code "char" NOT NULL,
    comfirmation boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.verification_for_jopseekers
(
    id integer NOT NULL,
    verification_code "char" NOT NULL,
    verfication boolean NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public."JopSeeker"
    ADD FOREIGN KEY ("jopseeker-id")
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.system_personnels
    ADD FOREIGN KEY (personnel_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.verification_for_employers (id)
    NOT VALID;


ALTER TABLE public.verification_for_employers
    ADD FOREIGN KEY (id)
    REFERENCES public.system_personnels (personnel_id)
    NOT VALID;


ALTER TABLE public.verification_for_jopseekers
    ADD FOREIGN KEY (id)
    REFERENCES public."JopSeeker" ("jopseeker-id")
    NOT VALID;


ALTER TABLE public.verification_for_jopseekers
    ADD FOREIGN KEY (id)
    REFERENCES public.system_personnels (personnel_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.recruitments ("position-id")
    NOT VALID;

END;